### PR TITLE
Bugfix/12 vi package is missing a vi

### PR DESCRIPTION
**Pull request by svelderrainruiz**
Malleable VI "Casting Utility For Actors.vim" was missing from the VI Package.

This closes issue  #12 
@niACS

### CODE REVIEW

**Comment by svelderrainruiz** [comment]
@niACS  can you please review this?

**Comment by elijah286** [comment]
It appears that both 1.0.0.8 and 1.0.1.10 are included. Remove the 1.0.0.8 so that there is no confusion

**Comment by elijah286** [comment]
I installed the package on my machine and verified it worked correctly. I did create a new issue #15

**Review by elijah286 — APPROVED** [review]
I installed it and verified it works. Please remove old package and see new issue for pallets #15

**Pull request merged**
